CREATE TABLE BROKER(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(50)
)

CREATE TABLE CUSTOMER(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	AMOUNT DECIMAL(20,2) NOT NULL DEFAULT(0),
	BROKER_ID INT NOT NULL,
	CONSTRAINT FK_CUSTOMER_BROKER FOREIGN KEY(BROKER_ID)
	REFERENCES BROKER(ID)
)

INSERT INTO BROKER(NAME) VALUES('Ted');
INSERT INTO BROKER(NAME) VALUES('Mark');
INSERT INTO BROKER(NAME) VALUES('Aaron');
INSERT INTO BROKER(NAME) VALUES('Luke');

INSERT INTO CUSTOMER(NAME, AMOUNT, BROKER_ID) VALUES('sam', 3000, 4);
INSERT INTO CUSTOMER(NAME, AMOUNT, BROKER_ID) VALUES('john', 4000, 2);
INSERT INTO CUSTOMER(NAME, AMOUNT, BROKER_ID) VALUES('mack', 5000, 2);
INSERT INTO CUSTOMER(NAME, AMOUNT, BROKER_ID) VALUES('test', 3000, 3);
INSERT INTO CUSTOMER(NAME, AMOUNT, BROKER_ID) VALUES('june', 2000, 3);
INSERT INTO CUSTOMER(NAME, AMOUNT, BROKER_ID) VALUES('mike', 4000, 1);
INSERT INTO CUSTOMER(NAME, AMOUNT, BROKER_ID) VALUES('annie', 4000, 2);
INSERT INTO CUSTOMER(NAME, AMOUNT, BROKER_ID) VALUES('micheal', 2000, 1);
INSERT INTO CUSTOMER(NAME, AMOUNT, BROKER_ID) VALUES('tom', 2000, 4);
INSERT INTO CUSTOMER(NAME, AMOUNT, BROKER_ID) VALUES('jason', 6000, 4);

SELECT
	b.NAME AS BROKER_NAME,
	COUNT(c.ID) AS CUSTOMER_COUNT
FROM
	CUSTOMER c
LEFT JOIN BROKER b ON
	c.BROKER_ID = b.ID
GROUP BY
	BROKER_ID
ORDER BY
	CUSTOMER_COUNT DESC,
	BROKER_NAME ASC;